#!/bin/bash

alias del="rm -rf"
alias update="source $HOME/.zshrc"
alias addignore='f() { echo "$@" >> .gitignore; unset -f f}; f'
alias c='cd'

if [[ $(which nvim) == *'not found' ]]; then
	alias v='vim'

else
	alias v='nvim'

fi

