#!/usr/bin/env python3

from random import choice
from string import ascii_letters, digits, punctuation

with open('key.txt', 'w') as f:
    for i in range(16):
        f.write(choice(f'{ascii_letters}{digits}{punctuation}'))
